apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlite-weather-pvc
  namespace: temperaturaapp
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlite-location-pvc
  namespace: temperaturaapp
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlite-person-pvc
  namespace: temperaturaapp
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 100Mi
