apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: temperaturaapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector-contrib:0.98.0
          ports:
            - containerPort: 4317   # gRPC
            - containerPort: 4318   # HTTP
            - containerPort: 8889   # Prometheus metrics
          volumeMounts:
            - name: config
              mountPath: /etc/otelcol-contrib
          resources:
            requests:
              memory: 64Mi
              cpu: 50m
            limits:
              memory: 256Mi
              cpu: 200m
      volumes:
        - name: config
          configMap:
            name: otel-collector-config
